/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewIdFlashcardsRouteImport } from './routes/review.$id.flashcards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdFlashcardsRoute = ReviewIdFlashcardsRouteImport.update({
  id: '/review/$id/flashcards',
  path: '/review/$id/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyse': typeof AnalyseRoute
  '/compose': typeof ComposeRoute
  '/result': typeof ResultRoute
  '/saved': typeof SavedRoute
  '/review/': typeof ReviewIndexRoute
  '/review/$id/flashcards': typeof ReviewIdFlashcardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyse': typeof AnalyseRoute
  '/compose': typeof ComposeRoute
  '/result': typeof ResultRoute
  '/saved': typeof SavedRoute
  '/review': typeof ReviewIndexRoute
  '/review/$id/flashcards': typeof ReviewIdFlashcardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyse': typeof AnalyseRoute
  '/compose': typeof ComposeRoute
  '/result': typeof ResultRoute
  '/saved': typeof SavedRoute
  '/review/': typeof ReviewIndexRoute
  '/review/$id/flashcards': typeof ReviewIdFlashcardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyse'
    | '/compose'
    | '/result'
    | '/saved'
    | '/review/'
    | '/review/$id/flashcards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyse'
    | '/compose'
    | '/result'
    | '/saved'
    | '/review'
    | '/review/$id/flashcards'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyse'
    | '/compose'
    | '/result'
    | '/saved'
    | '/review/'
    | '/review/$id/flashcards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyseRoute: typeof AnalyseRoute
  ComposeRoute: typeof ComposeRoute
  ResultRoute: typeof ResultRoute
  SavedRoute: typeof SavedRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ReviewIdFlashcardsRoute: typeof ReviewIdFlashcardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id/flashcards': {
      id: '/review/$id/flashcards'
      path: '/review/$id/flashcards'
      fullPath: '/review/$id/flashcards'
      preLoaderRoute: typeof ReviewIdFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyseRoute: AnalyseRoute,
  ComposeRoute: ComposeRoute,
  ResultRoute: ResultRoute,
  SavedRoute: SavedRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ReviewIdFlashcardsRoute: ReviewIdFlashcardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
