/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as ResultRouteImport } from './routes/result'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewIdFlashcardsRouteImport } from './routes/review.$id.flashcards'
import { Route as ReviewIdQuizRouteImport } from './routes/review.$id.quiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/review/',
  path: '/review/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdFlashcardsRoute = ReviewIdFlashcardsRouteImport.update({
  id: '/review/$id/flashcards',
  path: '/review/$id/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdQuizRoute = ReviewIdQuizRouteImport.update({
  id: '/review/$id/quiz',
  path: '/review/$id/quiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRoute
  '/compose': typeof ComposeRoute
  '/result': typeof ResultRoute
  '/saved': typeof SavedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/review/': typeof ReviewIndexRoute
  '/review/$id/flashcards': typeof ReviewIdFlashcardsRoute
  '/review/$id/quiz': typeof ReviewIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRoute
  '/compose': typeof ComposeRoute
  '/result': typeof ResultRoute
  '/saved': typeof SavedRoute
  '/account': typeof AuthenticatedAccountRoute
  '/review': typeof ReviewIndexRoute
  '/review/$id/flashcards': typeof ReviewIdFlashcardsRoute
  '/review/$id/quiz': typeof ReviewIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/analyse': typeof AnalyseRoute
  '/auth': typeof AuthRoute
  '/compose': typeof ComposeRoute
  '/result': typeof ResultRoute
  '/saved': typeof SavedRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/review/': typeof ReviewIndexRoute
  '/review/$id/flashcards': typeof ReviewIdFlashcardsRoute
  '/review/$id/quiz': typeof ReviewIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyse'
    | '/auth'
    | '/compose'
    | '/result'
    | '/saved'
    | '/account'
    | '/review/'
    | '/review/$id/flashcards'
    | '/review/$id/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyse'
    | '/auth'
    | '/compose'
    | '/result'
    | '/saved'
    | '/account'
    | '/review'
    | '/review/$id/flashcards'
    | '/review/$id/quiz'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/analyse'
    | '/auth'
    | '/compose'
    | '/result'
    | '/saved'
    | '/_authenticated/account'
    | '/review/'
    | '/review/$id/flashcards'
    | '/review/$id/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AnalyseRoute: typeof AnalyseRoute
  AuthRoute: typeof AuthRoute
  ComposeRoute: typeof ComposeRoute
  ResultRoute: typeof ResultRoute
  SavedRoute: typeof SavedRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
  ReviewIdFlashcardsRoute: typeof ReviewIdFlashcardsRoute
  ReviewIdQuizRoute: typeof ReviewIdQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/review/': {
      id: '/review/'
      path: '/review'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id/flashcards': {
      id: '/review/$id/flashcards'
      path: '/review/$id/flashcards'
      fullPath: '/review/$id/flashcards'
      preLoaderRoute: typeof ReviewIdFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id/quiz': {
      id: '/review/$id/quiz'
      path: '/review/$id/quiz'
      fullPath: '/review/$id/quiz'
      preLoaderRoute: typeof ReviewIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AnalyseRoute: AnalyseRoute,
  AuthRoute: AuthRoute,
  ComposeRoute: ComposeRoute,
  ResultRoute: ResultRoute,
  SavedRoute: SavedRoute,
  ReviewIndexRoute: ReviewIndexRoute,
  ReviewIdFlashcardsRoute: ReviewIdFlashcardsRoute,
  ReviewIdQuizRoute: ReviewIdQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
